#!/usr/bin/php
<?php
// ------------------------------------------------------------
// 
// BAN for nftables
// 
// T.Kabu/MyDNS.JP           http://www.MyDNS.JP/
// Future Versatile Group    http://www.fvg-on.net/
// 
// ver.1 ... Standalone type lockout service.
// ver.2 ... Information Sharing lockout service.
// ------------------------------------------------------------
?>
<?php
// ----------------------------------------------------------------------
// Init Routine
// ----------------------------------------------------------------------
require(__DIR__."/ban4nftd_init.php");
?>
<?php
// ----------------------------------------------------------------------
// Main Routine
// ----------------------------------------------------------------------

// プロセスをフォーク
$PID = pcntl_fork();
                
// フォークできなかったら
if ($PID == -1)
{
    // エラーメッセージに、プロセスをフォークできない旨を設定
    $ERR_MSG = 'Cannot fork process'.'!?';
    // メッセージを表示
    print "\n".'ban4nftd ... '.$ERR_MSG."\n\n";
    // 終わり
    exit -1;
}
// フォークできたら
else if ($PID != 0)
{
    // ここで終わり(あとはデーモン化したプロセスに任せる)
    exit;
}
// 子プロセス(＝デーモン)なら
else // if ($PID == 0)
{
    // 現在のプロセスをセッションリーダーにする
    $SID = posix_setsid();
    
    // セッションリーダーにできなかったら
    if ($SID < 0)
    {
        // エラーメッセージに、プロセスをセッションリーダーにできない旨を設定
        $ERR_MSG = 'Cannot set sid'.'!?';
        // メッセージを表示
        print "\n".'ban4nftd ... '.$ERR_MSG."\n\n";
        // 終わり
        exit -1;
    }
    // コアファイルを読み込んで、実際の処理を開始
    require(__DIR__.'/ban4nftd_core.php');
}
?>
